# Generated by Django 5.1.4 on 2024-12-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('categoria', models.CharField(choices=[('casa', 'Produtos de Casa'), ('mercado', 'Mercado'), ('padaria', 'Padaria'), ('farmacia', 'Farmácia'), ('lazer', 'Lazer'), ('poupanca', 'Poupança'), ('transporte', 'Transporte'), ('roupa', 'Roupa')], max_length=20, verbose_name='Categoria')),
                ('status_pagamento', models.CharField(choices=[('pago', 'Pago'), ('nao_pago', 'Não Pago')], max_length=10, verbose_name='Status de Pagamento')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
