# Generated by Django 5.1.4 on 2024-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='ano',
            field=models.IntegerField(default=2025, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='registro',
            name='mes',
            field=models.IntegerField(default=1, verbose_name='Mês'),
        ),
    ]
