# Generated by Django 5.1.4 on 2025-01-02 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registro_ano_registro_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='ano',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2025)], verbose_name='Ano'),
        ),
    ]
